version: '3'

services:

  nginx:
    image: nginx:1.25.4
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8088:80
    depends_on:
      - app
    container_name: test_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: test_app

  db:
    image: mysql:8.3.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8888:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-file /docker-entrypoint-initdb.d/init.sql
    container_name: test_mysql
